version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    volumes:
      - ./tasks_docs:/app/tasks_docs
      - ./sent_images:/app/sent_images
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - fastapi
    restart: always
