version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    volumes:
      - ./tasks_docs:/app/tasks_docs
      - ./sent_images:/app/sent_images
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - backend_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    restart: unless-stopped

networks:
  backend_net:
    driver: bridge
